# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run.
on:
  push:
        branches:
          - "master"
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=src" >> $GITHUB_ENV
        echo "${{ env.PYTHONPATH }}"
    - name: Set pystow dir
      run: |
        echo "DATA_PATH=$(python -c 'import moviegraphbenchmark; print(moviegraphbenchmark.create_graph.DATA_PATH)')" >> $GITHUB_ENV
    - name: Cache dataset downloads
      uses: actions/cache@v3
      with:
        # datasets are stored in `~/.data/moviegraphbenchmark/data`
        path: ${{ env.DATA_PATH }}
        key: ${{ runner.os }}-build-${{ matrix.python-version }}
        enableCrossOsArchive: True
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "${{ env.DATA_PATH }}"
    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo "It exists !"
    - name: Test
      run:
        nox
